<?php

return [

    'categories' => [
        'taj-mahal' => [
            'key' => 'agra',
            'slug' => 'taj-mahal',
            'city' => 'Agra',
            'title' => 'Taj Mahal Tours',
            'heading' => 'Taj Mahal & Agra Tours',
            'tagline' => 'City of the Taj Mahal',
            'icon' => 'fa-monument',
            'description' => 'Witness the Taj Mahal at sunrise, explore Agra Fort, Itimad-ud-Daulah & Fatehpur Sikri with expert local guides.',
            'banner' => 'cities/agra-banner.jpg',
            'card' => 'cities/agra-card.jpg',
            'tour_count' => '30+ tours',
            'monuments' => [
                ['name' => 'Taj Mahal', 'image' => 'monuments/agra-taj-mahal.jpg', 'desc' => 'UNESCO wonder — sunrise & sunset visits'],
                ['name' => 'Agra Fort', 'image' => 'monuments/agra-fort.jpg', 'desc' => 'Mughal red sandstone fortress'],
                ['name' => 'Fatehpur Sikri', 'image' => 'monuments/agra-fatehpur-sikri.jpg', 'desc' => 'Akbar\'s abandoned capital city'],
                ['name' => 'Itimad-ud-Daulah', 'image' => 'monuments/agra-baby-taj.jpg', 'desc' => 'The Baby Taj marble mausoleum'],
            ],
            'tours' => [
                ['title' => 'Sunrise Taj Mahal Tour from Delhi', 'duration' => '1 Day', 'price' => '1,750', 'rating' => 4.9, 'tag' => 'Best Seller', 'image' => 'monuments/agra-taj-mahal.jpg', 'highlights' => ['Sunrise entry', 'Private guide', 'Hotel pickup']],
                ['title' => 'Taj Mahal, Agra Fort & Fatehpur Sikri', 'duration' => '1 Day', 'price' => '4,580', 'rating' => 4.8, 'tag' => null, 'image' => 'monuments/agra-fort.jpg', 'highlights' => ['3 monuments', 'AC car', 'Lunch included']],
                ['title' => 'Overnight Taj Mahal & Agra Stay', 'duration' => '2 Days', 'price' => '3,200', 'rating' => 4.9, 'tag' => 'Popular', 'image' => 'monuments/agra-fatehpur-sikri.jpg', 'highlights' => ['Sunrise & sunset', 'Hotel stay', 'All transfers']],
                ['title' => 'Same Day Agra Tour by Train', 'duration' => '1 Day', 'price' => '2,100', 'rating' => 4.7, 'tag' => null, 'image' => 'monuments/agra-baby-taj.jpg', 'highlights' => ['Gatimaan Express', 'Guided tour', 'Meals optional']],
                ['title' => 'Private Taj Mahal Photography Tour', 'duration' => 'Half Day', 'price' => '1,450', 'rating' => 4.9, 'tag' => 'Top Rated', 'image' => 'monuments/agra-taj-mahal.jpg', 'highlights' => ['Best photo spots', 'Expert guide', 'Flexible timing']],
                ['title' => 'Taj Mahal & Baby Taj Combo', 'duration' => '1 Day', 'price' => '2,850', 'rating' => 4.8, 'tag' => null, 'image' => 'monuments/agra-baby-taj.jpg', 'highlights' => ['Two mausoleums', 'Skip-the-line', 'Private car']],
            ],
        ],

        'delhi' => [
            'key' => 'delhi',
            'slug' => 'delhi',
            'city' => 'New Delhi',
            'title' => 'New Delhi Tours',
            'heading' => 'New Delhi Heritage Tours',
            'tagline' => 'Capital of India',
            'icon' => 'fa-landmark',
            'description' => 'Discover Old Delhi\'s lanes, Red Fort, Qutub Minar, Humayun\'s Tomb & modern New Delhi with private guided tours.',
            'banner' => 'cities/delhi-banner.jpg',
            'card' => 'cities/delhi-card.jpg',
            'tour_count' => '25+ tours',
            'monuments' => [
                ['name' => 'Humayun\'s Tomb', 'image' => 'monuments/delhi-humayun-tomb.jpg', 'desc' => 'UNESCO Mughal garden tomb'],
                ['name' => 'Red Fort', 'image' => 'cities/delhi-card.jpg', 'desc' => 'Iconic Lal Qila of Old Delhi'],
                ['name' => 'Qutub Minar', 'image' => 'monuments/delhi-qutub-minar.jpg', 'desc' => '73m UNESCO minaret complex'],
                ['name' => 'India Gate', 'image' => 'monuments/delhi-india-gate.jpg', 'desc' => 'War memorial & Rajpath'],
            ],
            'tours' => [
                ['title' => 'Full Day Old & New Delhi Heritage Tour', 'duration' => '1 Day', 'price' => '1,450', 'rating' => 4.8, 'tag' => 'Best Seller', 'image' => 'monuments/delhi-humayun-tomb.jpg', 'highlights' => ['Old & New Delhi', 'Rickshaw ride', 'Private guide']],
                ['title' => 'Delhi Food Walk & Hidden Gems', 'duration' => 'Half Day', 'price' => '980', 'rating' => 4.7, 'tag' => null, 'image' => 'monuments/delhi-india-gate.jpg', 'highlights' => ['Chandni Chowk', 'Street food', 'Local stories']],
                ['title' => 'Private Delhi City Tour with Guide', 'duration' => '1 Day', 'price' => '1,890', 'rating' => 4.9, 'tag' => 'Top Rated', 'image' => 'monuments/delhi-qutub-minar.jpg', 'highlights' => ['Custom itinerary', 'AC vehicle', 'All monuments']],
                ['title' => 'Delhi to Agra Same Day Transfer + Taj', 'duration' => '1 Day', 'price' => '2,650', 'rating' => 4.8, 'tag' => 'Popular', 'image' => 'monuments/agra-taj-mahal.jpg', 'highlights' => ['Delhi pickup', 'Taj Mahal visit', 'Return same day']],
                ['title' => 'New Delhi Highlights Half Day', 'duration' => 'Half Day', 'price' => '890', 'rating' => 4.6, 'tag' => null, 'image' => 'monuments/delhi-india-gate.jpg', 'highlights' => ['India Gate', 'President House', 'Quick tour']],
            ],
        ],

        'jaipur' => [
            'key' => 'jaipur',
            'slug' => 'jaipur',
            'city' => 'Jaipur',
            'title' => 'Jaipur Tours',
            'heading' => 'Jaipur Pink City Tours',
            'tagline' => 'The Pink City',
            'icon' => 'fa-fort-awesome',
            'description' => 'Walk through royal palaces, Amber Fort, Hawa Mahal, City Palace & vibrant bazaars in Rajasthan\'s pink capital.',
            'banner' => 'cities/jaipur-banner.jpg',
            'card' => 'cities/jaipur-card.jpg',
            'tour_count' => '22+ tours',
            'monuments' => [
                ['name' => 'Amber Fort', 'image' => 'monuments/jaipur-amber-fort.jpg', 'desc' => 'Hilltop fort with elephant rides'],
                ['name' => 'Hawa Mahal', 'image' => 'monuments/jaipur-hawa-mahal.jpg', 'desc' => 'Palace of Winds facade'],
                ['name' => 'City Palace', 'image' => 'cities/jaipur-banner.jpg', 'desc' => 'Royal residence & museums'],
                ['name' => 'Jantar Mantar', 'image' => 'monuments/jaipur-hawa-mahal.jpg', 'desc' => 'UNESCO astronomical observatory'],
            ],
            'tours' => [
                ['title' => 'Jaipur Pink City Full Day Private Tour', 'duration' => '1 Day', 'price' => '2,100', 'rating' => 4.9, 'tag' => 'Best Seller', 'image' => 'monuments/jaipur-hawa-mahal.jpg', 'highlights' => ['Amber Fort', 'City Palace', 'Hawa Mahal']],
                ['title' => 'Amer Fort, Nahargarh & Jal Mahal Sunset', 'duration' => '1 Day', 'price' => '1,850', 'rating' => 4.8, 'tag' => null, 'image' => 'monuments/jaipur-amber-fort.jpg', 'highlights' => ['Sunset views', '3 forts', 'Private car']],
                ['title' => 'Jaipur Heritage Walk & Local Markets', 'duration' => 'Half Day', 'price' => '1,200', 'rating' => 4.7, 'tag' => 'Popular', 'image' => 'cities/jaipur-card.jpg', 'highlights' => ['Bazaars', 'Handicrafts', 'Local guide']],
                ['title' => 'Jaipur Food & Culture Tour', 'duration' => 'Half Day', 'price' => '1,100', 'rating' => 4.8, 'tag' => null, 'image' => 'cities/jaipur-banner.jpg', 'highlights' => ['Rajasthani cuisine', 'Pink City lanes', 'Tastings']],
                ['title' => 'Private Jaipur Day Trip from Delhi', 'duration' => '1 Day', 'price' => '3,500', 'rating' => 4.9, 'tag' => 'Top Rated', 'image' => 'monuments/jaipur-amber-fort.jpg', 'highlights' => ['Delhi pickup', 'Full Jaipur tour', 'Return same day']],
            ],
        ],

        'varanasi' => [
            'key' => 'varanasi',
            'slug' => 'varanasi',
            'city' => 'Varanasi',
            'title' => 'Varanasi Tours',
            'heading' => 'Varanasi Spiritual Tours',
            'tagline' => 'Spiritual Capital of India',
            'icon' => 'fa-om',
            'description' => 'Experience Ganga Aarti, sunrise boat rides, ancient temples & the sacred ghats of Kashi with knowledgeable guides.',
            'banner' => 'cities/varanasi-banner.jpg',
            'card' => 'cities/varanasi-card.jpg',
            'tour_count' => '18+ tours',
            'monuments' => [
                ['name' => 'Dashashwamedh Ghat', 'image' => 'monuments/varanasi-ghats.jpg', 'desc' => 'Main ghat for Ganga Aarti'],
                ['name' => 'Ganga Aarti', 'image' => 'monuments/varanasi-ganga-aarti.jpg', 'desc' => 'Evening lamp ceremony ritual'],
                ['name' => 'Sunrise Boat Ride', 'image' => 'monuments/varanasi-boat-ride.jpg', 'desc' => 'Dawn on the sacred Ganges'],
                ['name' => 'Kashi Vishwanath', 'image' => 'monuments/varanasi-ghats.jpg', 'desc' => 'Ancient Shiva temple corridor'],
            ],
            'tours' => [
                ['title' => 'Varanasi Ganga Aarti & Evening Tour', 'duration' => 'Half Day', 'price' => '890', 'rating' => 5.0, 'tag' => 'Best Seller', 'image' => 'monuments/varanasi-ganga-aarti.jpg', 'highlights' => ['Ganga Aarti', 'Ghat walk', 'Local guide']],
                ['title' => 'Sunrise Boat Ride & Temple Tour', 'duration' => '1 Day', 'price' => '1,150', 'rating' => 4.9, 'tag' => null, 'image' => 'monuments/varanasi-boat-ride.jpg', 'highlights' => ['Boat ride', 'Temples', 'Breakfast optional']],
                ['title' => 'Full Day Spiritual Varanasi Experience', 'duration' => '1 Day', 'price' => '1,680', 'rating' => 4.8, 'tag' => 'Top Rated', 'image' => 'monuments/varanasi-ghats.jpg', 'highlights' => ['Ghats & temples', 'Silk weaving', 'Aarti evening']],
                ['title' => 'Varanasi Walking Tour — Hidden Alleys', 'duration' => 'Half Day', 'price' => '750', 'rating' => 4.7, 'tag' => null, 'image' => 'monuments/varanasi-ghats.jpg', 'highlights' => ['Old city lanes', 'Local life', 'Small groups']],
                ['title' => '2-Day Varanasi Deep Dive', 'duration' => '2 Days', 'price' => '2,900', 'rating' => 4.9, 'tag' => 'Popular', 'image' => 'monuments/varanasi-boat-ride.jpg', 'highlights' => ['Sunrise & Aarti', 'Sarnath visit', 'Hotel assist']],
            ],
        ],

        'golden-triangle' => [
            'key' => 'golden-triangle',
            'slug' => 'golden-triangle',
            'city' => 'Golden Triangle',
            'title' => 'Golden Triangle Tours',
            'heading' => 'Golden Triangle Tour Packages',
            'tagline' => 'Delhi · Agra · Jaipur',
            'icon' => 'fa-route',
            'description' => 'Cover Delhi, Agra & Jaipur in one seamless journey — Taj Mahal, capital monuments & royal palaces with private car, guide & flexible itinerary.',
            'banner' => 'monuments/golden-triangle.jpg',
            'card' => 'monuments/golden-triangle.jpg',
            'tour_count' => '15+ packages',
            'monuments' => [
                ['name' => 'Taj Mahal, Agra', 'image' => 'monuments/agra-taj-mahal.jpg', 'desc' => 'India\'s most iconic monument'],
                ['name' => 'Delhi Monuments', 'image' => 'monuments/delhi-humayun-tomb.jpg', 'desc' => 'Capital heritage sites'],
                ['name' => 'Jaipur Palaces', 'image' => 'monuments/jaipur-amber-fort.jpg', 'desc' => 'Pink City royal forts'],
            ],
            'tours' => [
                ['title' => '3-Day Golden Triangle Tour', 'duration' => '3 Days', 'price' => '8,500', 'rating' => 4.9, 'tag' => 'Best Seller', 'image' => 'monuments/golden-triangle.jpg', 'highlights' => ['Delhi + Agra + Jaipur', 'Private AC car', 'Hotels optional']],
                ['title' => '4-Day Golden Triangle with Fatehpur Sikri', 'duration' => '4 Days', 'price' => '10,200', 'rating' => 4.8, 'tag' => 'Popular', 'image' => 'monuments/agra-fatehpur-sikri.jpg', 'highlights' => ['Extra day Agra', 'All monuments', 'Flexible pace']],
                ['title' => '5-Day Golden Triangle Deluxe', 'duration' => '5 Days', 'price' => '14,500', 'rating' => 4.9, 'tag' => 'Premium', 'image' => 'monuments/jaipur-amber-fort.jpg', 'highlights' => ['4-star hotels', 'Private guide each city', 'All entries']],
                ['title' => 'Same Day Taj + Jaipur from Delhi', 'duration' => '1 Day', 'price' => '5,800', 'rating' => 4.6, 'tag' => null, 'image' => 'monuments/agra-taj-mahal.jpg', 'highlights' => ['Long day trip', 'Taj + Amber Fort', 'Private car']],
                ['title' => '6-Day Golden Triangle + Varanasi', 'duration' => '6 Days', 'price' => '18,900', 'rating' => 4.9, 'tag' => 'Combo', 'image' => 'monuments/varanasi-ghats.jpg', 'highlights' => ['4 cities', 'Ganga Aarti', 'Complete North India']],
            ],
        ],
    ],

];
